# GitHub Pages configuration for MCP Portal
title: "MCP Portal - Model Context Protocol Hub"
description: "Comprehensive portal for MCP servers, clients, and development tools"
url: "https://mcp.collabnix.com"
baseurl: ""

# Theme
theme: null

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO
author: "Collabnix Community"
twitter:
  username: collabnix

# Social
social:
  name: "MCP Portal"
  links:
    - "https://github.com/collabnix/awesome-mcp-lists"
    - "https://twitter.com/collabnix"

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _headers
  - _redirects

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections_dir: collections

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"